//Action Creators
export const GET_TOWNS = 'VEHICLE_GET_TOWNS';
export const GET_COLORS = 'VEHICLE_GET_COLORS';
export const GET_IMAGES = 'VEHICLE_GET_IMAGES';
export const GET_VEHICLES = 'VEHICLE_GET_VEHICLES';
export const GET_VEHICLE_MAKES = 'VEHICLE_GET_VEHICLE_MAKES';
export const GET_VEHICLE_MODELS = 'VEHICLE_GET_VEHICLE_MODELS';
export const GET_VEHICLE_ENUMS = 'VEHICLE_GET_VEHICLE_ENUMS';

//Reducers
export const UPDATE_TOWNS = 'VEHICLE_UPDATE_TOWNS';
export const UPDATE_COLORS = 'VEHICLE_UPDATE_COLORS';
export const UPDATE_IMAGES = 'VEHICLE_UPDATE_IMAGES';
export const UPDATE_VEHICLES = 'VEHICLE_UPDATE_VEHICLES';
export const UPDATE_VEHICLE_MAKES = 'VEHICLE_UPDATE_VEHICLE_MAKES';
export const UPDATE_VEHICLE_MODELS = 'VEHICLE_UPDATE_VEHICLE_MODELS';
export const UPDATE_VEHICLE_ENUMS = 'VEHICLE_UPDATE_VEHICLE_ENUMS';