//Action Creators
export const GET_TOWNS = 'ADMINISTRATION_GET_TOWNS';
export const GET_COLORS = 'ADMINISTRATION_GET_COLORS';
export const GET_VEHICLE_MAKES = 'ADMINISTRATION_GET_VEHICLE_MAKES';
export const GET_VEHICLE_MODELS = 'ADMINISTRATION_GET_VEHICLE_MODELS';


//Reducers
export const UPDATE_TOWNS = 'ADMINISTRATION_UPDATE_TOWNS';
export const UPDATE_COLORS = 'ADMINISTRATION_UPDATE_COLORS';
export const UPDATE_VEHICLE_MAKES = 'ADMINISTRATION_UPDATE_VEHICLE_MAKES';
export const UPDATE_VEHICLE_MODELS = 'ADMINISTRATION_UPDATE_VEHICLE_MODELS';