//Action Creators
export const GET_VEHICLE = 'VEHICLE_GET_VEHICLE';
export const GET_VEHICLES = 'VEHICLE_GET_VEHICLES';
export const GET_VEHICLE_MAKES = 'VEHICLE_GET_VEHICLE_MAKES';
export const GET_VEHICLE_MODELS = 'VEHICLE_GET_VEHICLE_MODELS';

//Reducers
export const UPDATE_VEHICLE = 'VEHICLE_UPDATE_VEHICLE';
export const UPDATE_VEHICLES = 'VEHICLE_UPDATE_VEHICLES';
export const UPDATE_VEHICLE_MAKES = 'VEHICLE_UPDATE_VEHICLE_MAKES';
export const UPDATE_VEHICLE_MODELS = 'VEHICLE_UPDATE_VEHICLE_MODELS';
