//Action Creators
export const GET_TOWNS = 'ADMINISTRATION_GET_TOWNS';
export const GET_COLORS = 'ADMINISTRATION_GET_COLORS';

//Reducers
export const UPDATE_TOWNS = 'ADMINISTRATION_UPDATE_TOWNS';
export const UPDATE_COLORS = 'ADMINISTRATION_UPDATE_COLORS';